language: ruby
rvm:
  - 2.6
before_script:
	- yes | gem update --system --force
  - gem install bundler
  - bundle install
script:
  - wl=https://awesome.re
  - awesome_bot README.md -w=$wl
  - bundle exec danger
